# frozen_string_literal: true

source 'http://rubygems.org'

ruby '2.5.0'

gem 'fixer'
gem 'oj'
gem 'rack-cors'
gem 'rake'
gem 'rufus-scheduler'
gem 'sequel_pg'
gem 'sinatra', '>= 4.1.0'
gem 'unicorn'

group :development do
  gem 'minitest'
  gem 'minitest-around'
  gem 'rack-test'
  gem 'rubocop'
end
